# fly.toml app configuration file generated for hono-expense-demo on 2024-09-21T00:40:13+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hono-expense-demo'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
